# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ef95889f770d340a8fc8c4bc5b4cba7c"
name = "ripemetrics-chatbot"
handle = "ripemetrics-chatbot-1"
application_url = "https://accommodations-surrey-penalty-genetics.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "ripe-andrews-dev.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://accommodations-surrey-penalty-genetics.trycloudflare.com/auth/callback",
  "https://accommodations-surrey-penalty-genetics.trycloudflare.com/auth/shopify/callback",
  "https://accommodations-surrey-penalty-genetics.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
