# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "70bb18e886844dd98f18586b1475d371"
name = "RipeMetrics"
handle = "ripemetrics-2"
application_url = "https://ski-informative-nylon-registry.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "ripe-andrews-dev.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://ski-informative-nylon-registry.trycloudflare.com/auth/callback",
  "https://ski-informative-nylon-registry.trycloudflare.com/auth/shopify/callback",
  "https://ski-informative-nylon-registry.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
